name: win

on:
  - push
  - workflow_dispatch
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: true
      matrix:
        name: [
          "windows-py39",
        ]
        
        include:
          - name: "windows-py39"
            python-version: "3.9"
            os: windows-latest
            arch: x86-64
          - name: "windows-py39"
            python-version: "3.9"
            os: windows-latest
            arch: arm64

    steps:
    - uses: actions/checkout@v2
    
    - name: git clone PyDev.Debugger
      run: |
        cd ..
        git clone https://github.com/fabioz/PyDev.Debugger.git
#         cd PyDev.Debugger
#         git checkout py311_939
        
    - name: Compile attach to process on Windows x86-64
      shell: cmd
      if: matrix.arch == x86-64
      run: |
        cd ..\PyDev.Debugger\pydevd_attach_to_process\windows
        compile_windows.bat
        
    - name: Compile attach to process on Windows arm64
      shell: cmd
      if: matrix.arch == arm64
      run: |
        cd ..\PyDev.Debugger\pydevd_attach_to_process\windows
        compile_windows_arm64.bat

    - name: Copy files to upload
      shell: cmd
      run: |
        copy ..\PyDev.Debugger\pydevd_attach_to_process\*.pdb .
        copy ..\PyDev.Debugger\pydevd_attach_to_process\*.exe .
        copy ..\PyDev.Debugger\pydevd_attach_to_process\*.dll .
        dir
                
    - uses: actions/upload-artifact@v2
      with:
        name: win_binaries_${{ matrix.arch }}
        if-no-files-found: error
        path: |
          *.pdb
          *.exe
          *.dll
